### ISSUE TITLE
Proposal: Sticky items

### ISSUE THREAD

**Issue by ghost** [catamphetamine/virtual-scroller#12]
It will be nice to be able set any items to be sticky, a little like "position: sticky" css property.

When you scroll down the list and you meet item set as sticky to top, then this item will be always visible on top of container - if scrollTop is equal to item position or greater.

Same with sticky to bottom, item will be always visible on bottom of container - if scrollTop + containerHeight is equal to item position + itemHeight or higher.

https://www.w3schools.com/howto/howto_css_sticky_element.asp

**Comment by catamphetamine** [comment]
It’s not clear what you’re proposing.

**Comment by ghost** [comment]
Updated, sorry for too short explanation.

**Comment by catamphetamine** [comment]
It’s still not clear to me what you want.
You can provide an online demo if you want.

**Comment by ghost** [comment]
Here is example of top sticky items: (pay attention to headers in list "a", "b", "c", ...)

https://codepen.io/simevidas/pen/JbdJRZ

Here is example of bottom sticky items: (pay attention to gray footer with save button)

https://codepen.io/jaakritso/pen/zMXRaw

**Comment by catamphetamine** [comment]
I see, so your point is that this library only supports non-sticky list
items.
It is for simplicity.
If you want some items be sticky, then they can be rendered not as part of
VirtualScroller: before it or after it.

**Comment by catamphetamine** [comment]
So this one is actually not about sticky items or whatever. It's about [scrollable containers](https://github.com/catamphetamine/virtual-scroller/issues/8) other than `window`. I'll reopen that issue.

**Comment by ghost** [comment]
Does VirtualScroller listen for container resized? By ResizeObserver for example?

**Comment by catamphetamine** [comment]
It does listen to `window` `"resize"` event.
If there'll be scrollable parents then I guess `ResizeObserver` (on modern browsers) could be used to track item visibility.
