### ISSUE TITLE
Is this virtual scroller the reason why we can't copy all the content from the webpage?

### ISSUE THREAD

**Issue by silicium2020** [catamphetamine/virtual-scroller#13]
I have a friend who told me that twitter use this code to let the chrome charge less content. This gives you an advantage of faster view speed and less ram consumption. However, if we want to turn off this scroller to copy some pages, what should we do? Thanks

**Comment by catamphetamine** [comment]
> However, if we want to turn off this scroller to copy some pages, what should we do?

I guess, just re-render the page in `bypass` mode.

**Comment by catamphetamine** [comment]
Currently there's no dynamic handling of `bypass` option due to the user experience being subpart when a page freezes to render a 1000 items or so.

**Comment by silicium2020** [comment]
> > However, if we want to turn off this scroller to copy some pages, what should we do?
> 
> I guess, just re-render the page in `bypass` mode.

OK i am trying to find out what bypass mode mean for now. Will try it later and tell you the result

**Comment by silicium2020** [comment]
> Currently there's no dynamic handling of `bypass` option due to the user experience being subpart when a page freezes to render a 1000 items or so.

If you means that we could refresh the page bypass the caches use ctrl + f5, i just tried that and it doesn't work on my side. I wonder if i understand the bypass in the right way..

**Comment by catamphetamine** [comment]
@silicium2020 If you're using a React component then there's a `bypass` property there.
The DOM component has a `bypass` option too.
That's what "bypass".

**Comment by silicium2020** [comment]
Thank you for your patience, since i know very little thing on programming, i asked a friend to show me how to do that.  I will add the update in the next 3 days. thanks
