### ISSUE TITLE
How does the measureItemsBatchSize really does its measurement?

### ISSUE THREAD

**Issue by davie1989** [catamphetamine/virtual-scroller#20]
Hello, 

I am using this library in my project to render news feed. The library is awesome. Kudos to you guys.

I have a kind of a peculiar use case where some images or videos will have different sizes. Some will display longer than the others just like we have it Facebook. So, currently, I am using min-height:320px instead of a fix height or aspect-ratio.

However, when I do that, I realize that when I am currently on the feed that is displaying a long image and the I navigate to another screen, when I navigate back, sometimes, I lost the image original position before I navigated away.

So, I decided to increase the  VirtualScroller measureItemsBatchSize props to 1000 and that seem to be helpful a little.

I want to know how the measureItemsBatchSize: number — The measureItemsBatchSize option of VirtualScroller really does it's measurement so I can use that as a clue to set an approximate value.

Also, I noticed that when I have scrolled so much into the feed... Let's say I have scrolled to about 200 feeds, and then I navigate to another screen, navigating back becomes very slow meanwhile the number of elements on the DOM is still very few as expected. I guess it is the top calculation that is causing the delay in re-mounting.

Thanks.

**Comment by catamphetamine** [comment]
> I lost the image original position before I navigated away.

That's correct.

For that to not happen, save `virtual-scroller` state in `onStateChange()` property function and then pass the saved state back to a re-created `<VirtualScroller/>` by providing a `state` property.

> So, I decided to increase the VirtualScroller `measureItemsBatchSize` props to 1000 and that seem to be helpful a little.

That would only make it "load" faster when navigating to a page and then scrolling down by a large distance. I guess that's your case too.

> navigating back becomes very slow

I guess what is perceived by "slow" is actually the complete re-rendering of a long list of items while being scrolled down by a large distance. That's when `measureItemsBatchSize` has an effect.

But, as I've said at the start of this comment, prefer state restoration when navigating Back if it's a "Single-Page Application".
Anything other than that would be sub-optimal and would introduce unneeded work on the web browser.

**Comment by davie1989** [comment]
Hello @catamphetamine , I seem to already have that in place before. And actually, re-created virtual-scroller was extremely fast. I am saving the state in SessionStorage.

                    //onStateChange={state => virtualScrollerState.current = state}
                    //initialState={history?.action === "POP" ? readScrollerState() : undefined}

But I commented it because I am using virtual-scroller in a lot of places hence need to ensure that the saved state for each virtual-scroller instance is unique. I'll just uncomment it again.

Thanks for your kind and helpful response.
