### ISSUE TITLE
VirtualScroller React Api

### ISSUE THREAD

**Issue by felixmosh** [catamphetamine/virtual-scroller#4]
Hi,

First of all thank you for this lib 🙏🏼

I'm not sure how this
```
<VirtualScroller
   id="messages"
   items={messages}
   itemComponent={Message}
   preserveScrollPosition/>
```

defined the amount of items that should be rendered.
Is this defined by the passed items?

**Comment by catamphetamine** [comment]
> I'm not sure how this defined the amount of items that should be rendered.

By default, it renders all items visible in the `3 * screenHeight` region centered at the screen's center.

https://github.com/catamphetamine/virtual-scroller/blob/3ba4702bfa2334e7553f35bfb3f0c1dd1fe2f583/source/VirtualScroller.js#L739-L744

https://github.com/catamphetamine/virtual-scroller/blob/3ba4702bfa2334e7553f35bfb3f0c1dd1fe2f583/source/VirtualScroller.js#L223-L228

**Comment by felixmosh** [comment]
Thanx for explaining it
