### ISSUE TITLE
[Question] Multiple items in a row

### ISSUE THREAD

**Issue by felixmosh** [catamphetamine/virtual-scroller#6]
I have a list of cards.
In mobile, the list renders one card in a row VirtualScroller handle it properly, but, in desktop, it gets spreaded, and may render different number of cards in a "row" (depends on the screen width).

There is any way to specify that to the lib, so calculations will be adjusted?

Thanx

**Comment by catamphetamine** [comment]
Hi.
Currently, there's no way to do that.
You can group your cards in small groups and render a group as a whole instead of each card individually.

**Comment by catamphetamine** [comment]
Added the feature in version `1.6.0`.

https://gitlab.com/catamphetamine/virtual-scroller#grid-layout

https://catamphetamine.gitlab.io/virtual-scroller/index-grid.html
