### ISSUE TITLE
awesome job ❤👍👋✌

### ISSUE THREAD

**Issue by himadrinath** [catamphetamine/virtual-scroller#9]
i tried react-virtualized and also react-window before i find about this library those two are very complicated lots of extra config. once i tried your i just config and it worked like magic. thanks to u.

few question

1. i am using with next.js and i want to render my first page load (ssr) with every item in list not just first one because of google crawler and indexing and then when user start to scroll then virtualization can start effect. can i do this may be some where in the options where i can config number of item i want to load in my first initial load.

2. my list component shared by multiple pages and i store last scroll position of those pages so that when user come back those pages i can scroll in that last visited position. what are my options to do that using virual-scroll

**Comment by catamphetamine** [comment]
Hi.

> i am using with next.js and i want to render my first page load (ssr) with every item in list not just first one because of google crawler and indexing and then when user start to scroll then virtualization can start effect. can i do this may be some where in the options where i can config number of item i want to load in my first initial load.

The current code is:

```js
	getEstimatedItemsCountOnScreen() {
		if (typeof window !== 'undefined') {
			return this.getEstimatedItemsCount(window.innerHeight)
		} else {
			return 1
		}
	}
```

So on server side it's `1`.

I've documented the `bypass: boolean` property/option.
Published `virtual-scroller@1.1.0`.
See if `bypass: true` works in your case.

> my list component shared by multiple pages and i store last scroll position of those pages so that when user come back those pages i can scroll in that last visited position. what are my options to do that using virual-scroll

Inside `state` there's `scrollY` property.
It exposes the current page scroll Y.
I've added an automatic page `scrollY` restoration on mount if a previously captured `state` was passed.

**Comment by himadrinath** [comment]
ok i will test this out ..................
i tried others libraries but your magic.... many many thanks...

**Comment by himadrinath** [comment]
bypass working. 

one down

scrollY yet to test

another to go........

**Comment by himadrinath** [comment]
how can i change the state without component mount

**Comment by catamphetamine** [comment]
@himadrinath What do you mean

**Comment by himadrinath** [comment]
how can i update the state within the component itself.

**Comment by catamphetamine** [comment]
Why would you want to hack the component's state

**Comment by himadrinath** [comment]
because when user change the page the component did not unmount its just update so i have to set the new state accordingly with that prevs state if its have one

**Comment by catamphetamine** [comment]
It's not clear what your use case is and why do you want to hack the component's state.
The component can be rendered with a `key` to re-mount it when the `key` changes.

**Comment by himadrinath** [comment]
something like that
```
class PageList extends React.Component{
constructor(props){
super(props)
      this.state={
      state: undefined
      }
}

componentDidUpdate(){
// update the state
}

return (
const {state}= this.state
<VirtualScroller
items={someArray}
state={state && state} />
)
}
```

**Comment by catamphetamine** [comment]
It's still not clear why would you want to modify the component's state directly.

**Comment by himadrinath** [comment]
its because when user go one to another page by href  i want restore the scroll prev position if the user already visited the page... 

i want restore last visited position not only just by back button

**Comment by catamphetamine** [comment]
I'll close this issue for now, because it's an unrelated discussion.
I guess it won't be clear what you mean, partially because of your English, and partially because you provide no illustration.
